// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI9sMydXSx1I9pSpfQVpZN6cJKhU-85Y4',
    appId: '1:350942136323:web:0091a3db72d160b58a2636',
    messagingSenderId: '350942136323',
    projectId: 'homepharma-45879',
    authDomain: 'homepharma-45879.firebaseapp.com',
    storageBucket: 'homepharma-45879.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuExFdUkALsASRkQvVgohm9OicbFxbm00',
    appId: '1:350942136323:android:35c57333d554fc9a8a2636',
    messagingSenderId: '350942136323',
    projectId: 'homepharma-45879',
    storageBucket: 'homepharma-45879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Ga5WUXSviREbUEGCgLbyLnn3gNW3f4s',
    appId: '1:350942136323:ios:34619958a36a540a8a2636',
    messagingSenderId: '350942136323',
    projectId: 'homepharma-45879',
    storageBucket: 'homepharma-45879.firebasestorage.app',
    iosBundleId: 'com.example.homepharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Ga5WUXSviREbUEGCgLbyLnn3gNW3f4s',
    appId: '1:350942136323:ios:34619958a36a540a8a2636',
    messagingSenderId: '350942136323',
    projectId: 'homepharma-45879',
    storageBucket: 'homepharma-45879.firebasestorage.app',
    iosBundleId: 'com.example.homepharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI9sMydXSx1I9pSpfQVpZN6cJKhU-85Y4',
    appId: '1:350942136323:web:fec245126b375f748a2636',
    messagingSenderId: '350942136323',
    projectId: 'homepharma-45879',
    authDomain: 'homepharma-45879.firebaseapp.com',
    storageBucket: 'homepharma-45879.firebasestorage.app',
  );
}
